### PR TITLE
Fix Phoenix parameter filtering

### LINKED ISSUE #649: all request_headers are filtered out by default
Hello friends! Long time no see 👋 

## Describe the bug

We're getting no HTTP header information in our bug traces, not even the [defaults](https://docs.appsignal.com/elixir/configuration/options.html#option-request_headers) which are specified as `["accept", "accept-charset", "accept-encoding", "accept-language", "cache-control", "connection", "content-length", "path-info", "range", "request-method", "request-uri", "server-name", "server-port", "server-protocol"]`

We haven't configured the http_headers anywhere (full text search for appsignal on the App and checked our environment variables)

## To Reproduce

- Using AppSignal for Elixir package version 2.1.6
- used with phoenix and the phoenix integration
- do not configure request headers anywhere
- tigger error notification
- no request headers 😭 

Screenshot 2021-05-11 at 17 09 56

## Diagnosis

I believe this was introduced by #637 making the default return value of request_headers an empty list because as the [docs say](https://docs.appsignal.com/elixir/configuration/options.html#option-request_headers):

>  To configure AppSignal to not store any HTTP request headers on AppSignal transactions, configure the option with an empty list.

## Ask

Please let me know if the default will be restored or if this change is intended in which case I'll make it explicit in our app and an update to the docs would be great 😁  Or, let me know where I went wrong 👀 

-------------------------

Anyhow, 
thank you all! 💚 

IMG_20180525_145837

### PR DESCRIPTION
**Pull request by unflxw**
Before this change, all sample data was passed through the `Appsignal.Utils.MapFilter.filter/1` function, which filters the given map by the allowlist specified in the `:filter_parameters` Phoenix configuration key, when it exists and is an allowlist.

This commit changes the behaviour of the `set_sample_data/3` function so that it only filters the sample data when the given key is `"params"`. This fixes #649.

### CODE REVIEW

**Review by tombruijn — APPROVED** [review]

File: lib/appsignal/span.ex [hunk 1]
```diff
@@ -190,18 +190,23 @@ defmodule Appsignal.Span do
...
 
   """
-  def set_sample_data(%Span{reference: reference} = span, key, value)
-      when is_binary(key) and is_map(value) do
-    data =
-      value
-      |> Appsignal.Utils.MapFilter.filter()
-      |> Appsignal.Utils.DataEncoder.encode()
+  def set_sample_data(span, "params" = key, value) do
+    do_set_sample_data(span, key, Appsignal.Utils.MapFilter.filter(value))
```
Comment (jeffkreeftmeijer) [inline lib/appsignal/span.ex:194]: When matching on `"params"`, we can use `"params"` in the function clause’s body instead of putting it into a variable.

**Review by jeffkreeftmeijer — APPROVED** [review]
