### PR TITLE
Move compilation helper functions to mix_helpers.exs

### LINKED ISSUE #288: (UndefinedFunctionError) function Appsignal.System.agent_platform/0 is undefined or private
Hi,

After updating appsignal-elixir from 1.3.5 to 1.4.5 I get this error message while doing a deployment:
```
remote: could not compile dependency :appsignal, "mix compile" failed. You can recompile this dependency with "mix deps.compile appsignal", update it with "mix deps.update appsignal" or clean it with "mix deps.clean appsignal"
remote: ==> appsignal
remote: ** (UndefinedFunctionError) function Appsignal.System.agent_platform/0 is undefined or private
remote:     Appsignal.System.agent_platform()
remote:     mix_helpers.exs:12: Mix.Appsignal.Helper.verify_system_architecture/0
remote:     /tmp/build/deps/appsignal/mix.exs:17: Mix.Tasks.Compile.Appsignal.run/1
remote:     (mix) lib/mix/task.ex:301: Mix.Task.run_task/3
remote:     (elixir) lib/enum.ex:1270: Enum."-map/2-lists^map/1-0-"/2
remote:     (mix) lib/mix/tasks/compile.all.ex:19: anonymous fn/1 in Mix.Tasks.Compile.All.run/1
remote:     (mix) lib/mix/tasks/compile.all.ex:37: Mix.Tasks.Compile.All.with_logger_app/1
remote:     (mix) lib/mix/task.ex:301: Mix.Task.run_task/3
```

We use Herokuish on Ubuntu with these build packs:
https://github.com/HashNuke/heroku-buildpack-elixir.git                         
https://github.com/gjaldon/heroku-buildpack-phoenix-static.git 

```
cat elixir_buildpack.config
 erlang_version=20.1                                                             
 elixir_version=1.5.2                                                            
 always_rebuild=false                                                            
 runtime_path=/app 

cat phoenix_static_buildpack.config
 phoenix_relative_path=apps/app-name                                     
 assets_path=../../assets                                                        
 phoenix_ex=phx  
```

Please let me know what else you want to know... :-)

Any ideas how to fix this?
Thx!

### PR DESCRIPTION
**Pull request by jeffkreeftmeijer**
Closes #288.

Instead of precompiling `Appsignal.Server` and `Appsignal.Agent` and using their functions from the compilation mix task, this patch moves the logic used for compilation the `mix_helpers.exs`, to make sure no older versions of the compiled libraries are used when compiling newer versions.

### CODE REVIEW

**Comment by tombruijn** [comment]
I'll make the change in the agent repo for the `agent.exs` rename and move.

File: lib/appsignal.ex [hunk 1]
```diff
@@ -42,6 +42,16 @@ defmodule Appsignal do
...
 
+  def agent_version do
+    case :appsignal
+    |> :code.priv_dir
+    |> Path.join("appsignal.version")
+    |> File.read do
+      {:ok, contents} -> String.trim(contents)
+      _ -> nil
+    end
+  end
```
Comment (tombruijn) [inline lib/appsignal.ex]: Let's move this to `Appsignal.Nif`?

File: mix.exs [hunk 2]
```diff
@@ -33,8 +26,6 @@ defmodule Mix.Tasks.Compile.Appsignal do
     end
 
     purge_module Appsignal.Agent
```
Comment (tombruijn) [inline mix.exs]: Would this purge still be necessary?

File: test/appsignal/system_test.exs [hunk 3]
```diff
@@ -41,85 +36,6 @@ defmodule Appsignal.SystemTest do
...
-      with_mocks([
-        {System,
-          [:passthrough],
-          [cmd: fn(_, _, _) -> {"ldd: illegal option -- -", 1} end]
-        }
-      ]) do
-        assert Appsignal.System.agent_platform() == "freebsd"
-      end
-    end
-  end
```
Comment (tombruijn) [inline test/appsignal/system_test.exs]: These tests are still quite useful. Can we test this somewhere else instead?

**Comment by tombruijn** [comment]
@jeffkreeftmeijer ready to merge?
