### PR TITLE
Check agent version in Mix.Appsignal.Helper.ensure_downloaded/1

### LINKED ISSUE #138: Mix.Appsignal.Helper.ensure_downloaded/1 does not overwrite old agent versions
After upgrading appsignal to 0.12.1, I got an error as starting my phoenix server in production(Amazon Linux): 

```
[debug] Appsignal starting.
[error] Error loading NIF, Appsignal integration disabled!

Failed to load NIF library: '/home/ec2-user/myapp/_build/prod/lib/appsignal/priv/appsignal_extension.so: undefined symbol: appsignal_running_in_container'

Is your operating system (x86_64-unknown-linux-gnu) supported?
Please check http://docs.appsignal.com/support/operating-systems.html
```

It works fine when appsignal's version is 0.11.6

Is it a bug or Am I doing something wrong?

### PR DESCRIPTION
**Pull request by jeffkreeftmeijer**
Closes #138. Needs a new version of the agent that includes a file named appsignal.version that holds the agent build's revision. 

TODO:

- [x] Update agent version once available
- [x] Test locally with old agents installed

**Note**: this is a hotfix on master.

### CODE REVIEW

File: mix_helpers.exs [hunk 1]
```diff
@@ -130,8 +130,22 @@ defmodule Mix.Appsignal.Helper do
     List.to_string(path)
   end
 
+  defp priv_path(filename) do
+    priv_dir() <> "/" <> filename
```
Comment (tombruijn) [inline mix_helpers.exs]: Can we use `Path.join()` for this?
