### PR TITLE
⌨️ Add Dialyzer to CI build, fix warnings

### LINKED ISSUE #234: ⌨️ Add Dialyzer to build
So we don't throw any warnings.

- http://erlang.org/doc/man/dialyzer.html
- https://github.com/jeremyjh/dialyxir

Continuation of https://github.com/appsignal/appsignal-elixir/issues/165

### LINKED ISSUE #270: Dialyzer error on 1.3.4
I just upgraded from 1.2.3 to 1.3.4, and now I'm seeing a dialyzer error: `lib/error_tracker.ex:26: Function track/4 has no local return`. Here is my track function and a helper function:

```elixir
  def track(error, message, stack, metadata) do
    IO.warn inspect metadata
    Appsignal.send_error(error, message, stack, to_meta(metadata))
    :ok
  end

  def to_meta(data) when is_map(data) do
    for {key, value} <- data, into: %{}, do: {key, inspect(value)}
  end
  def to_meta(data), do: %{arguments: inspect(data)}

```

Pretty simple, and I didn't change anything in those functions when I updated. I suspect the internal workings of the `send_error` function changed in a way dialyzer didn't like, but I didn't see anything obvious when I looked at the diff on github. Any ideas?

### PR DESCRIPTION
**Pull request by jeffkreeftmeijer**
Closes #234.
Closes #270.

Dialyzer is a code checker / lynter. If you're nice you won't get warnings. Someone got errors in their project because of AppSignal, were not sure why, so we fixed all Dialyzer warnings!

### CODE REVIEW

File: lib/appsignal/transaction.ex [hunk 1]
```diff
@@ -63,7 +63,7 @@ defmodule Appsignal.Transaction do
   `Appsignal.TransactionRegistry`.
 
   """
-  @spec start(String.t, String.t) :: Transaction.t
+  @spec start(String.t, atom) :: Transaction.t
```
Comment (tombruijn) [inline lib/appsignal/transaction.ex]: would we maybe want to allow a Sting type here, and use remove the `Atom.to_string(namespace)` on the line below? Or maybe always call `to_string(namespace)` on it and allow both Atoms and Strings?

Not sure if changing the type would break things for people who now pass in Strings, or would that not work at all?

File: lib/appsignal/phoenix.ex [hunk 2]
```diff
@@ -46,7 +46,9 @@ if Appsignal.phoenix? do
       # explicitly remove the transaction here so the regular error handler doesn't submit it again
       :ok = TransactionRegistry.remove_transaction(transaction)
 
-      Logger.debug("Submitting Phoenix error #{inspect transaction}: #{message}")
+      Logger.debug(fn() ->
+        "Submitting Phoenix error #{inspect transaction}: #{message}"
+      end)
```
Comment (tombruijn) [inline lib/appsignal/phoenix.ex]: Not sure I understand this one. What does this fix by passing a function to the logger? I can't get dialyzer to list a problem if I undo this change

Comment (jeffkreeftmeijer) [reply lib/appsignal/phoenix.ex]: Sorry, this one slipped in and is a fix for a Credo issue, not for Dialyzer. For `Logger.debug/1` calls with interpolation, passing a function with no argument is [preferred](https://github.com/rrrene/credo/issues/299). Not an issue in our case, but since it's enforced by Credo, we might as well follow its advice.

File: lib/appsignal/transaction.ex (hunk 1 above)
Comment (jeffkreeftmeijer) [reply lib/appsignal/transaction.ex]: The type spec makes our choice to use an atom explicit, and will allow us to check to make sure the library is calling its own functions properly. The type specs don't have an effect on the code itself. 

We've always expected an atom here (passing a string to `Atom.to_string/1` will crash), the type spec was just incorrect, causing a lot of Dialyzer warnings.
