### PR TITLE
Always return :ok from Appsignal.config_change/3

### LINKED ISSUE #779: Exception after upgrade to version 2.2.14
## Describe the bug

I think there is an issue in the `config_change` function implementation.
The function `initialize`, called at https://github.com/appsignal/appsignal-elixir/blob/ab876253936838369654f11bbcd387a7c52c3994/lib/appsignal.ex#L57 does not always return `:ok`, and so i get the following exception:
```
MatchError: ** (MatchError) no match of right hand side value: nil
lib/appsignal.ex:57 in anonymous fn/0 in Appsignal.config_change/3
```
The elixir logger does return `:ok`, but some of the calls to the elixir logger have been changed to the Appsignal logger, which doesn't return `:ok`

For example at lines 
https://github.com/appsignal/appsignal-elixir/blob/ab876253936838369654f11bbcd387a7c52c3994/lib/appsignal.ex#L73 and https://github.com/appsignal/appsignal-elixir/blob/ab876253936838369654f11bbcd387a7c52c3994/lib/appsignal.ex#L75

- Using AppSignal for Elixir package version 2.2.14

### PR DESCRIPTION
**Pull request by jeffkreeftmeijer**
In some situations, Appsignal.config_change/3 didn’t produce the expected `:ok` response. This patch makes sure it always does. It also includes fixes and type specs for the Logger, which also didn’t always return the expected `:ok`

Closes #779.

### CODE REVIEW

**Review by unflxw — APPROVED** [review]
Thanks for adding typespecs to the logger! I neglected to do that when implementing it.

The change for `config_change/3` looks good as well, modulo fixing the tests -- not sure what can be done about the failing assertions in the release upgrade test, since it relies on the PID that the function used to return before the change.

**Review by luismiramirez — APPROVED** [review]

File: lib/appsignal.ex [hunk 1]
```diff
@@ -53,12 +53,15 @@ defmodule Appsignal do
     # calling itself once it reached `Application.put_env` in
     # `Appsignal.Config`.
     spawn(fn ->
-      :ok = Appsignal.Nif.stop()
-      :ok = initialize()
+      Appsignal.Nif.stop()
+      initialize()
     end)
+
+    :ok
```
Comment (tombruijn) [inline lib/appsignal.ex:60]: Looks like this breaks the `release_upgrade_test` because it expects the PID to be returned and it no longer does that.

Comment (tombruijn) [reply lib/appsignal.ex:60]: I tried to make the test pass another way, by checking which new PID was alive after the config_change function was called, but at random times some tests register more than one new PID and it's difficult to determine which is the one we want to know about. Not sure how else to track this.

```patch
From edc67142d52d964ecda6df8c72ac58e9528b91b6 Mon Sep 17 00:00:00 2001
From: Tom de Bruijn <tom@tomdebruijn.com>
Date: Mon, 18 Jul 2022 11:46:22 +0200
Subject: [PATCH] Fix release_upgrade test after config_change

The config_change function no longer returns a PID. Because of that we
don't know the PID of the new spawned process to monitor.

Alternatively the config_change function can return a tuple of
`{:ok, pid}`, but I'm not sure if that would work. I'm unfamiliar with
the return value this function, but the docs it only returns `:ok`.

https://hexdocs.pm/elixir/1.13.4/Application.html#c:config_change/3
---
 test/appsignal/release_upgrade_test.exs | 14 +++++++++++++-
 1 file changed, 13 insertions(+), 1 deletion(-)

diff --git test/appsignal/release_upgrade_test.exs test/appsignal/release_upgrade_test.exs
index 0410e6d6..28e241a5 100644
--- test/appsignal/release_upgrade_test.exs
+++ test/appsignal/release_upgrade_test.exs
@@ -24,8 +24,20 @@ test "config_change/3" do
         |> Map.put(:name, "AppSignal test suite app v2")

       with_config(new_config, fn ->
+        pids_before = Process.list()
         # Hot reload / upgrade
-        config_reload_pid = Appsignal.config_change([], [], [])
+        Appsignal.config_change([], [], [])
+
+        pids_after = Process.list()
+        new_pids = pids_after -- pids_before
+
+        if length(new_pids) > 1 do
+          raise "More than one new process started (#{length(new_pids)}).
+            There should only be one new process, otherwise we can't tell
+            which one restarted the config."
+        end
+
+        config_reload_pid = List.first(new_pids)
         # The config is reloaded in a separate process so we wait for it here
         assert Process.alive?(config_reload_pid)

--
2.36.0
```

Comment (unflxw) [reply lib/appsignal.ex:60]: I suppose it could be split in two: `do_config_change`, which returns `pid`, and `config_change`, a wrapper that calls `do_config_change`, ignores its return value, and returns `:ok`. Then we test `do_config_change`, and not its wrapper, the way we did before.

**Comment by jeffkreeftmeijer** [comment]
Fixed in https://github.com/appsignal/appsignal-elixir/pull/782/commits/70738aaa7dcc20e115b59ab8f75cd6eb47fd6f55.

**Review by tombruijn — APPROVED** [review]
Let's ship this together tomorrow with PR #786

**Review by unflxw — APPROVED** [review]

**Review by luismiramirez — APPROVED** [review]
