### PR TITLE
Check Appsignal.started?/1 in TransactionRegistry.lookup/2

### LINKED ISSUE #53: Error running ecto data update migrations with Appsignal installed
I'm trying to run a migration which simply updates the values of a particular table column using Repo.update_all, but when Appsignal is active, it throws the following error:

```elixir
** (ArgumentError) argument error
    (stdlib) :ets.lookup(:"$appsignal_transaction_registry", #PID<0.73.0>)
    lib/appsignal/transaction/registry.ex:46: Appsignal.TransactionRegistry.lookup/2
    lib/appsignal/ecto.ex:23: Appsignal.Ecto.log/1
    (db_connection) lib/db_connection.ex:1177: DBConnection.log/6
    (ecto) lib/ecto/adapters/postgres/connection.ex:78: Ecto.Adapters.Postgres.Connection.prepare_execute/5
    (ecto) lib/ecto/adapters/sql.ex:235: Ecto.Adapters.SQL.sql_call/6
    (ecto) lib/ecto/adapters/sql.ex:424: Ecto.Adapters.SQL.execute_and_cache/7
    (stdlib) timer.erl:197: :timer.tc/3
```

I've got the `Appsignal.Ecto` logger configured via:

```elixir
config :hoffer, MyApp.Repo,
  loggers: [Appsignal.Ecto]
```

This is on:

```
elixir: 1.3.4
ecto: 2.0.6
appsignal: 0.9.2
```
The workaround for me with this was to remove the `Appsignal.Ecto` logger config so that the migration could run, and then re-enable it again.

Do let me know what other information might be helpful, I'll get them across as soon as possible.

### PR DESCRIPTION
**Pull request by jeffkreeftmeijer**
Closes #53.

### CODE REVIEW

File: lib/appsignal/transaction/registry.ex [hunk 1]
```diff
@@ -43,14 +43,16 @@ defmodule Appsignal.TransactionRegistry do
...
+    if Appsignal.started? do
+      case :ets.lookup(@table, pid) do
+        [{^pid, :removed}] ->
+          case return_removed do
+            false -> nil
+            true -> :removed
+          end
+        [{^pid, transaction}] -> transaction
+        [] -> nil
+      end
```
Comment (arjan) [inline lib/appsignal/transaction/registry.ex]: Adding an `else` clause would be more explicit here (to return `nil`).

Alternatively you can do a shortcircuit using `case Appsignal.started? && :ets.lookup(@table.pid) do` (with a `false ->` clause added) to keep the indentation on the same level.

**Comment by arjan** [comment]
Can you see if you can fix the test before merging?
