### PR TITLE
Open and close Transactions in Appsignal.Phoenix.Plug.call/2

### LINKED ISSUE #117: Samples are missing events
Some samples seem to be missing events from the sample.

I can reproduce this in the [jeffkreeftmeijer/appsignal-phoenix-example](https://github.com/jeffkreeftmeijer/appsignal-phoenix-example) app. @jeffkreeftmeijer you can also find an example of this event timeline in your own test apps organization under the "appsignal_phoenix_example" app `dev` env.

image

The "dash"/"indenting line" before the event name shouldn't be there for the first event. Apparently there's an event above it we don't track?

This is how it should look:

image

This sample event data comes from the agent, so there is something going wrong there.

We need to check and test to see if there's a scenario that crashes or breaks the transaction in some way that it misses events.

---

## Possibly related problem from the Ruby gem

We had a similar issue before in the Ruby gem for Sinatra apps where the transaction wasn't completed properly (it crashed), then a new request came in and transactions overlapped requests. That way the events that were monitored on one sample could be from one or more requests.

The PR that described that problem and fixed it: https://github.com/appsignal/appsignal-ruby/pull/145

The same probably occurs here: https://app.intercom.io/a/apps/yzor8gyw/inbox/all/conversations/7981810773

----

sorry if the description doesn't make a ton of sense, I'll try to expand on the problem later.

### PR DESCRIPTION
**Pull request by jeffkreeftmeijer**
Closes #117.

### CODE REVIEW

File: lib/appsignal/phoenix/instrumenter.ex [hunk 1]
```diff
@@ -52,34 +26,50 @@ if Appsignal.phoenix? do
...
-    def maybe_transaction_start_event(%{}, args) do
-      maybe_transaction_start_event(self(), args)
+
+    @doc false
+    def phoenix_controller_call(:stop, _diff, {%Transaction{} = transaction, %{conn: conn} = args}) do
+      Transaction.finish_event(
+        transaction,
+        "phoenix_controller_call",
+        "phoenix_controller_call",
+        args,
```
Comment (arjan) [inline lib/appsignal/phoenix/instrumenter.ex]: On master, I explicitly remove `:conn` from `args` before sending it to `finish_event` (see the `cleanup_args` function)

Comment (arjan) [inline lib/appsignal/phoenix/instrumenter.ex]: same goes for the other event

File: lib/appsignal/phoenix/instrumenter.ex [hunk 2]
```diff
@@ -52,34 +26,50 @@ if Appsignal.phoenix? do
...
     @doc false
-    def cleanup_args(args) do
-      Map.delete(args, :conn)
+    def phoenix_controller_render(:stop, _diff, nil), do: nil
+    def phoenix_controller_render(:stop, _diff, {transaction, args}) do
+      Transaction.finish_event(
+        transaction,
+        "phoenix_controller_render",
+        "phoenix_controller_render",
+        args,
```
Comment (arjan) [inline lib/appsignal/phoenix/instrumenter.ex]: this one

File: lib/appsignal/phoenix/instrumenter.ex [hunk 3]
```diff
@@ -52,34 +26,50 @@ if Appsignal.phoenix? do
...
     end
-    def maybe_transaction_start_event(nil, _), do: nil
 
     @doc false
-    def maybe_transaction_finish_event(_event, nil), do: nil
-    def maybe_transaction_finish_event(event, {transaction, args}) do
-      Transaction.finish_event(transaction, event, event, args, 0)
+    def phoenix_controller_render(:start, _compiled, args) do
+      transaction = Appsignal.TransactionRegistry.lookup(self())
+      {Transaction.start_event(transaction), args}
```
Comment (arjan) [inline lib/appsignal/phoenix/instrumenter.ex]: You can call `start_event()` without parameters here, it will to the lookup inside the Transaction module.

**Comment by arjan** [comment]
I just had a realisation.

When the transaction is started only at the start of the controller, it will be impossible to instrument everything that goes on before the controller, e.g. plugs that are being called from the router. (many plugs like that do DB queries for authorization etc that you wanna measure).

So this is my suggestion:
* Reinstate `Appsignal.Phoenix.Plug` to start the transaction 
* Keep the Phoenix controller start/end instrumentation hooks to record the event
* Stop the transaction in the `phoenix_controller_call(:stop`.
* Document `Appsignal.Phoenix.Plug` so that people do not use it mistakenly without adding the Phoenix instrumenter -- because with the above approach the setup is assymetrical (transaction started in the plug but ended in the instrumentation hook).

File: lib/appsignal/phoenix/instrumenter.ex [hunk 4]
```diff
@@ -18,68 +18,49 @@ if Appsignal.phoenix? do
...
+    @transaction Application.get_env(:appsignal, :appsignal_transaction, Appsignal.Transaction)
 
-    alias Appsignal.Transaction
+    @doc false
+    def phoenix_controller_call(:start, _, args), do: start_event(args)
 
-    require Logger
+    @doc false
+    def phoenix_controller_call(:stop, _diff, {%Appsignal.Transaction{} = transaction, %{conn: conn} = args}) do
+      finish_event(transaction, "phoenix_controller_call", args)
```
Comment (tombruijn) [inline lib/appsignal/phoenix/instrumenter.ex]: We discussed changing this name so that it doesn't get put in the "other" group. Can we change this to the event name `controller_call.phoenix`?

File: lib/appsignal/phoenix/instrumenter.ex [hunk 5]
```diff
@@ -18,68 +18,49 @@ if Appsignal.phoenix? do
...
-    def maybe_transaction_finish_event(event, {transaction, args}) do
-      Transaction.finish_event(transaction, event, event, args, 0)
-    end
+    def phoenix_controller_render(:start, _, args), do: start_event(args)
 
     @doc false
-    def cleanup_args(args) do
-      Map.delete(args, :conn)
+    def phoenix_controller_render(:stop, _diff, {%Appsignal.Transaction{} = transaction, args}) do
+      finish_event(transaction, "phoenix_controller_render", args)
```
Comment (tombruijn) [inline lib/appsignal/phoenix/instrumenter.ex]: We discussed changing this name so that it doesn't get put in the "other" group. Can we change this to the event name `controller_render.phoenix`?

**Comment by jeffkreeftmeijer** [comment]
Updated, and ready for re-review once more.
