### PR TITLE
Use only supported TLS versions

### LINKED ISSUE #714: Compiling AppSignal quietly fails
I'm hosting the application on Gigalixir. When deploying the code with AppSignal 2.2.7 and AppSignal Phoenix 2.0.13, I see the following errors in the output:

```
==> appsignal
       Downloading agent release
remote: AppSignal installation failed: Could not download archive from any of our mirrors.
remote: Please make sure your network allows access to any of these mirrors.
remote: Attempted to download the archive from the following urls:
remote: - URL: https://appsignal-agent-releases.global.ssl.fastly.net/09308fb/appsignal-x86_64-linux-all-static.tar.gz
remote: - Error (hackney response):
remote: {:error, {:options, {:insufficient_crypto_support, {:"tlsv1.3", {:versions, [:"tlsv1.3", :"tlsv1.2"]}}}}}
remote:
remote: - URL: https://d135dj0rjqvssy.cloudfront.net/09308fb/appsignal-x86_64-linux-all-static.tar.gz
remote: - Error (hackney response):
remote: {:error, {:options, {:insufficient_crypto_support, {:"tlsv1.3", {:versions, [:"tlsv1.3", :"tlsv1.2"]}}}}}
       Compiling 44 files (.ex)
remote: warning: Error loading NIF (Is your operating system (x86_64-unknown-linux-gnu) supported? Please check http://docs.appsignal.com/support/operating-systems.html):
remote: Failed to load NIF library: '/tmp/build/_build/prod/lib/appsignal/priv/appsignal_extension.so: cannot open shared object file: No such file or directory'
remote:   lib/appsignal/nif.ex:23: Appsignal.Nif.init/0
remote:   (kernel 7.3) code_server.erl:1355: anonymous fn/1 in :code_server.handle_on_load/5
remote:
       Generated appsignal app
```

It does not stop the deployment. The application starts, but AppSignal does not work. I see that it logs the following errors on start:

```
...: web.1  | warning: Error loading NIF (Is your operating system (x86_64-unknown-linux-gnu) supported? Please check http://docs.appsignal.com/support/operating-systems.html):
...: web.1  | Failed to load NIF library: '/app/lib/appsignal-2.2.7/priv/appsignal_extension.so: cannot open shared object file: No such file or directory'
...: web.1  |   anonymous fn/1 in :init.run_on_load_handlers/2
...: web.1  |
...: web.1  |   (appsignal 2.2.7) lib/appsignal/nif.ex:23: Appsignal.Nif.init/0
...: web.1  | 13:15:26.160 application=appsignal function=initialize/0 module=Appsignal [error] Failed to start AppSignal. Please run the diagnose task (https://docs.appsignal.com/elixir/command-line/diagnose.html) to debug your installation.
```

I'm using gigalixir-stack-18 which runs on Ubuntu 18.x. It works fine after rolling back to AppSignal 2.2.3 and AppSignal Phoenix 2.0.12.

### PR DESCRIPTION
**Pull request by unflxw**
Ask the SSL module for a list of supported TLS versions for Hackney to attempt to use during the agent download, so that versions that are unsupported by Elixir's currently linked "cryptolib" (that is, OpenSSL) are not listed in the `:versions` option.

This fixes #714, an issue where downloading the agent will fail when using OpenSSL 1.0.2, as the download attempts to use the TLS versions listed in `:versions` _in order_, and errors out when it attempts to use TLS 1.3, which isn't supported by the cryptolib.

The same changes to the TLS options used in the agent download are also applied to `Appsignal.Transmitter`, which is used to validate API keys and send the diagnose report.

### CODE REVIEW

**Comment by unflxw** [comment]
I attempted to add a run to CI where it attempts to run the tests with OpenSSL 1.0.2, but it seems like the versions of Elixir installed by `sem-version` are statically linked to OpenSSL 1.1.1, and compiling our own Erlang would be a time-expensive addition to the CI, so I didn't do this in the end.

Since the code for the SSL options is full of conditionals depending on the OTP version, I attempted to test every possible branch of those conditions with both OpenSSL 1.0.2 and 1.1.1 in Docker. I can confirm that it's working fine for OTP versions 21 to 24, but I could not confirm 20.0 and 20.3 because they are only compatible with Elixir up to 1.9, and the integration does not compile in Elixir 1.9 at the moment.

File: mix_helpers.exs [hunk 1]
```diff
@@ -704,7 +704,12 @@ defmodule Mix.Appsignal.Helper do
   end
 
   if System.otp_release() >= "23" do
-    defp tls_options, do: [versions: [:"tlsv1.3", :"tlsv1.2"]]
+    defp tls_options do
+      accepted = [:"tlsv1.3", :"tlsv1.2"]
+      supported = :ssl.versions()[:supported]
+
+      [versions: Enum.filter(accepted, &Enum.member?(supported, &1))]
```
Comment (unflxw) [inline mix_helpers.exs:711]: This could probably just be `[versions: :ssl.versions()[:supported]]` instead? That would already be `[:"tlsv1.3", :"tlsv1.2"]` on OpenSSL 1.1.1 and `[:"tlsv1.2"]` on OpenSSL 1.0.2.

I went for the "playing it safe" approach, but I'm not sure we need to play it safe here, selecting the supported ones out of a list of "accepted" TLS versions -- if a new TLS version was added tomorrow, it would only be on `:ssl.versions()[:supported]` if the cryptolib supported it, and in that case, it should be safe to list it and try to use it, even if the download mirror servers didn't support it yet. Thoughts?

Comment (luismiramirez) [reply mix_helpers.exs:711]: I don't have strong opinions on this. The "playing it safe" approach you implemented looks good to me, we can keep it.

**Review by luismiramirez — APPROVED** [review]

File: mix_helpers.exs [hunk 2]
```diff
@@ -704,7 +704,12 @@ defmodule Mix.Appsignal.Helper do
   end
 
   if System.otp_release() >= "23" do
-    defp tls_options, do: [versions: [:"tlsv1.3", :"tlsv1.2"]]
+    defp tls_options do
```
Comment (tombruijn) [inline mix_helpers.exs:707]: If we change this, I still need to test and review it in more detail, we also need to change it in the diagnose report transmission.

File: mix_helpers.exs (hunk 1 above)
Comment (tombruijn) [reply mix_helpers.exs:711]: Your playing it safe would prevent any very bad and old SSL versions being used, so that's a plus, but it may also require more maintenance in the future when we need to add more versions. We could also leave it to the user to use the best versions. We don't make this decision in other integrations and just use whatever the language is compiled with. So I'm also okay with directly using `:ssl.versions()[:supported]`

Comment (unflxw) [reply mix_helpers.exs:711]: @tombruijn 

> Your playing it safe would prevent any very bad and old SSL versions being used, so that's a plus

Somewhat surprisingly, `:ssl.versions()[:supported]` already takes care of that! In this case, "supported" _also_ means "not deprecated". TLS 1.1 and their other "bad and old" friends are present in `:ssl.versions()[:available]`, but not in `:supported`.

Comment (tombruijn) [reply mix_helpers.exs:711]: @unflxw Awesome! Then use that I guess :)

File: mix_helpers.exs (hunk 2 above)
Comment (unflxw) [reply mix_helpers.exs]: Added the same change to `Appsignal.Transmitter` as well.

File: mix_helpers.exs (hunk 1 above)
Comment (unflxw) [reply mix_helpers.exs]: Using that. 👍

**Review by tombruijn — APPROVED** [review]

**Review by jeffkreeftmeijer — APPROVED** [review]
