### PR TITLE
DataEncoder encodes bignums as strings

### LINKED ISSUE #88: Long integers in parameters trigger errors in AppSignal NIF
When having long integers inside parameters (in our case, keystrokes typed by a user on a phone) AppSignal's NIF throws a `(ArgumentError) argument error`.

### Backtrace
```(appsignal) Appsignal.Nif._data_set_integer("", "keystrokes", 112122121122111122222211122112122)
(elixir) lib/enum.ex:657: anonymous fn/3 in Enum.each/2
(stdlib) lists.erl:1262: :lists.foldl/3
(elixir) lib/enum.ex:656: Enum.each/2
(appsignal) lib/appsignal/utils/data_encoder.ex:16: Appsignal.Utils.DataEncoder.encode/1
(appsignal) lib/appsignal/transaction.ex:209: Appsignal.Transaction.set_sample_data/3
(appsignal) lib/appsignal/transaction.ex:378: Appsignal.Transaction.set_request_metadata/2
(appsignal) lib/appsignal/phoenix/plug.ex:23: anonymous fn/2 in Appsignal.Phoenix.Plug.call/2```

### PR DESCRIPTION
**Pull request by jeffkreeftmeijer**
Closes #88.

### CODE REVIEW

File: lib/appsignal/utils/data_encoder.ex [hunk 1]
```diff
@@ -31,6 +31,9 @@ defmodule Appsignal.Utils.DataEncoder do
   def encode(resource, {key, value}) when is_binary(value) do
     Nif.data_set_string(resource, key, value)
   end
+  def encode(resource, {key, value}) when is_integer(value) and value >= 9223372036854775808 do
+    Nif.data_set_string(resource, key, "bignum:#{value}")
```
Comment (tombruijn) [inline lib/appsignal/utils/data_encoder.ex]: I used `bigint:` in the ruby gem: https://github.com/appsignal/appsignal-ruby/pull/234
probably a good idea to give them the same prefix.

Comment (jeffkreeftmeijer) [inline lib/appsignal/utils/data_encoder.ex]: Haha, yes, that's what I meant. Fixed in b34b68667444ddacce33074b182397115fffe520. :+1:
